///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : cameradata.h
/// SOFTWARE COMPONENT NAME           : CameraData
/// GENERATED DATE                    : 2024-11-07 14:01:17
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_AA_GEN_SOFTWARE_COMPONENT_PPORT_CAMERA_AA_CAMERADATA_H
#define PARA_AA_GEN_SOFTWARE_COMPONENT_PPORT_CAMERA_AA_CAMERADATA_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "deepracer/service/cameradata/svcameradata_skeleton.h"
 
#include "ara/log/logger.h"
 
#include <opencv2/opencv.hpp>
#include <mutex>
#include <thread>
 
namespace deepracer
{
namespace service
{
namespace cameradata
{
namespace skeleton
{
 
class SvCameraDataSkeletonImpl : public SvCameraDataSkeleton
{
public:
    /// @brief Constructor
    SvCameraDataSkeletonImpl(ara::core::InstanceSpecifier instanceSpec, ara::com::MethodCallProcessingMode mode = ara::com::MethodCallProcessingMode::kEvent);
    
    
    
private:
    /// @brief Logger for this port
    ara::log::Logger& m_logger;
    
    
};
 
} /// namespace skeleton
} /// namespace cameradata
} /// namespace service
} /// namespace deepracer

namespace camera
{
namespace aa
{
namespace port
{
 
class CameraData
{
public:
    /// @brief Constructor
    CameraData();
    
    /// @brief Destructor
    ~CameraData();
    
    /// @brief Start port
    void Start();
    
    /// @brief Terminate port
    void Terminate();
    
    /// @brief Write event data to buffer, CEvent
    void WriteDataCEvent(const deepracer::service::cameradata::skeleton::events::CEvent::SampleType& data);
     
    /// @brief Send event cyclic from buffer data, CEvent
    void SendEventCEventCyclic();
     
    /// @brief Send event directly from buffer data, CEvent
    void SendEventCEventTriggered();
     
    /// @brief Send event directly with argument, CEvent
    void SendEventCEventTriggered(const deepracer::service::cameradata::skeleton::events::CEvent::SampleType& data);

    bool scanCameraIndex(const std::vector<int32_t>& cameraIdxList);

    void produceFrames();

    int64_t getCurrentTimestamp() const;
     
private:
    /// @brief Logger for this port
    ara::log::Logger& m_logger;
    
    /// @brief Flag of port status
    bool m_running;
    
    /// @brief Mutex for this port
    std::mutex m_mutex;
    
    /// @brief AUTOSAR Port Interface
    std::shared_ptr<deepracer::service::cameradata::skeleton::SvCameraDataSkeletonImpl> m_interface;
    
    /// @brief Data for event, CEvent
    deepracer::service::cameradata::skeleton::events::CEvent::SampleType m_CEventData;

    std::vector<cv::VideoCapture> videoCaptureList_;
};
 
} /// namespace port
} /// namespace aa
} /// namespace camera
 
#endif /// PARA_AA_GEN_SOFTWARE_COMPONENT_PPORT_CAMERA_AA_CAMERADATA_H