///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : fusiondata.cpp
/// SOFTWARE COMPONENT NAME           : FusionData
/// GENERATED DATE                    : 2024-10-25 13:47:26
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "inference/aa/port/fusiondata.h"
 
namespace inference
{
namespace aa
{
namespace port
{
 
FusionData::FusionData()
    : m_logger(ara::log::CreateLogger("INFR", "PORT", ara::log::LogLevel::kVerbose))
    , m_running{false}
    , m_found{false}
{
}
 
FusionData::~FusionData()
{
}
 
void FusionData::Start()
{
    m_logger.LogVerbose() << "FusionData::Start";
    
    // regist callback
    // Find Service에 대한 핸들러 정의 -> 서비스 찾는 과정
    ara::core::InstanceSpecifier specifier{"Inference/AA/FusionData"};
    auto handler = [this](ara::com::ServiceHandleContainer<deepracer::service::fusiondata::proxy::SvFusionDataProxy::HandleType> handles,
                          ara::com::FindServiceHandle findHandle) {
        this->Find(handles, findHandle);
    };
    
    // find service : Find Service 호출
    auto find = deepracer::service::fusiondata::proxy::SvFusionDataProxy::StartFindService(handler, specifier);
    if (find.HasValue())
    {
        m_logger.LogVerbose() << "FusionData::Start::StartFindService";
    }
    else
    {
        m_logger.LogError() << "FusionData::Start::StartFindService::" << find.Error().Message();
    }
    
    // run port
    m_running = true;
}
 
// FPort 종료 처리 함수
void FusionData::Terminate()
{
    m_logger.LogVerbose() << "FusionData::Terminate";
    
    // stop port
    m_running = false;
    
    // clear service proxy
    if (m_interface)
    {   
        // method는 R-R이기 때문에 Stop Sub 할 필요가 없다.
        
        // stop find service
        m_interface->StopFindService(*m_findHandle);
        m_found = false;
        
        m_logger.LogVerbose() << "FusionData::Terminate::StopFindService";
    }
}

// Find Service에 대한 핸들러 함수
void FusionData::Find(ara::com::ServiceHandleContainer<deepracer::service::fusiondata::proxy::SvFusionDataProxy::HandleType> handles, ara::com::FindServiceHandle findHandle)
{
    // check finding handles
    // 찾고자 하는 핸들 체크
    // 만약 핸들이 없다면 해당 함수는 return 된다.
    if (handles.empty())
    {
        m_logger.LogVerbose() << "FusionData::Find::Service Instances not found";
        return;
    }
    else
    {
        for (auto& handle : handles)
        {
            m_logger.LogVerbose() << "FusionData::Find::Searched Instance::ServiceId =" << 
                                     handle.GetServiceHandle().serviceId << 
                                     ", InstanceId =" << 
                                     handle.GetServiceHandle().instanceId;
        }
    }
    
    // create proxy
    // Proxy 생성 : 핸들러가 이미 존재하는지 체크
    if (m_interface)
    {
        m_logger.LogVerbose() << "FusionData::Find::Proxy is already running";
    }
    else
    {
        m_logger.LogVerbose() << "FusionData::Find::Using Instance::ServiceId =" << 
                                 handles[0].GetServiceHandle().serviceId << 
                                 ", InstanceId =" << 
                                 handles[0].GetServiceHandle().instanceId;
        m_interface = std::make_shared<deepracer::service::fusiondata::proxy::SvFusionDataProxy>(handles[0]);
        m_findHandle = std::make_shared<ara::com::FindServiceHandle>(findHandle);
        m_found = true;
        

        // 이 아래에서 Event, Field는 Sub 요청을 보낸다
        // 여기 // 
    }
}


// FMethod 처리에 대한 Request 및 Result 처리 함수
void FusionData::RequestFMethod(const deepracer::type::SensorFusionNode& sensorfusion)
{
    if (m_found)
    {
        auto request = m_interface->FMethod(sensorfusion);
        request.wait();
        auto response = request.GetResult();
        if (response.HasValue())
        {
            m_logger.LogVerbose() << "FusionData::RequestFMethod::Responded";
            
            auto result = response.Value();
            // put your logic
            
            if (m_receiveMethodFMethodHandler != nullptr)
            {
                m_receiveMethodFMethodHandler(result);
            }
        }
        else
        {
            m_logger.LogError() << "FusionData::RequestFMethod::" << response.Error().Message();
        }
    }
}

void FusionData::SetReceiveMethodFMethodHandler(
    std::function<void(const deepracer::service::fusiondata::proxy::methods::FMethod::Output&)> handler)
{
    m_receiveMethodFMethodHandler = handler;
}

 
} /// namespace port
} /// namespace aa
} /// namespace inference
 
/// EOF