///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : fusiondata.cpp
/// SOFTWARE COMPONENT NAME           : FusionData
/// GENERATED DATE                    : 2024-11-13 13:00:52
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "inference/aa/port/fusiondata.h"
 
namespace inference
{
namespace aa
{
namespace port
{
 
FusionData::FusionData()
    : m_logger(ara::log::CreateLogger("INFR", "PORT", ara::log::LogLevel::kVerbose))
    , m_running{false}
    , m_found{false}
{
}
 
FusionData::~FusionData()
{
}
 
void FusionData::Start()
{
    m_logger.LogVerbose() << "FusionData::Start";
    
    // regist callback
    ara::core::InstanceSpecifier specifier{"Inference/AA/FusionData"};
    auto handler = [this](ara::com::ServiceHandleContainer<deepracer::service::fusiondata::proxy::SvFusionDataProxy::HandleType> handles,
                          ara::com::FindServiceHandle findHandle) {
        this->Find(handles, findHandle);
    };
    
    // find service
    auto find = deepracer::service::fusiondata::proxy::SvFusionDataProxy::StartFindService(handler, specifier);
    if (find.HasValue())
    {
        m_logger.LogVerbose() << "FusionData::Start::StartFindService";
    }
    else
    {
        m_logger.LogError() << "FusionData::Start::StartFindService::" << find.Error().Message();
    }
    
    // run port
    m_running = true;
}
 
void FusionData::Terminate()
{
    m_logger.LogVerbose() << "FusionData::Terminate";
    
    // stop port
    m_running = false;
    
    // clear service proxy
    if (m_interface)
    {
        // stop subscribe
        StopSubscribeFEvent();
        
        // stop find service
        m_interface->StopFindService(*m_findHandle);
        m_found = false;
        
        m_logger.LogVerbose() << "FusionData::Terminate::StopFindService";
    }
}
 
void FusionData::Find(ara::com::ServiceHandleContainer<deepracer::service::fusiondata::proxy::SvFusionDataProxy::HandleType> handles, ara::com::FindServiceHandle findHandle)
{
    // check finding handles
    if (handles.empty())
    {
        m_logger.LogVerbose() << "FusionData::Find::Service Instances not found";
        return;
    }
    else
    {
        for (auto& handle : handles)
        {
            m_logger.LogVerbose() << "FusionData::Find::Searched Instance::ServiceId =" << 
                                     handle.GetServiceHandle().serviceId << 
                                     ", InstanceId =" << 
                                     handle.GetServiceHandle().instanceId;
        }
    }
    
    // create proxy
    if (m_interface)
    {
        m_logger.LogVerbose() << "FusionData::Find::Proxy is already running";
    }
    else
    {
        m_logger.LogVerbose() << "FusionData::Find::Using Instance::ServiceId =" << 
                                 handles[0].GetServiceHandle().serviceId << 
                                 ", InstanceId =" << 
                                 handles[0].GetServiceHandle().instanceId;
        m_interface = std::make_shared<deepracer::service::fusiondata::proxy::SvFusionDataProxy>(handles[0]);
        m_findHandle = std::make_shared<ara::com::FindServiceHandle>(findHandle);
        m_found = true;
        
        // subscribe events
        SubscribeFEvent();
    }
}
 
void FusionData::SubscribeFEvent()
{
    if (m_found)
    {
        // regist receiver handler
        // if you want to enable it, please uncomment below code
        // 
        // RegistReceiverFEvent();
        
        // request subscribe
        auto subscribe = m_interface->FEvent.Subscribe(1);
        if (subscribe.HasValue())
        {
            m_logger.LogVerbose() << "FusionData::SubscribeFEvent::Subscribed";
        }
        else
        {
            m_logger.LogError() << "FusionData::SubscribeFEvent::" << subscribe.Error().Message();
        }
    }
}
 
void FusionData::StopSubscribeFEvent()
{
    if (m_found)
    {
        // request stop subscribe
        m_interface->FEvent.Unsubscribe();
        m_logger.LogVerbose() << "FusionData::StopSubscribeFEvent::Unsubscribed";
    }
}
 
void FusionData::RegistReceiverFEvent()
{
    if (m_found)
    {
        // set callback
        auto receiver = [this]() -> void {
            return ReceiveEventFEventTriggered();
        };
        
        // regist callback
        auto callback = m_interface->FEvent.SetReceiveHandler(receiver);
        if (callback.HasValue())
        {
            m_logger.LogVerbose() << "FusionData::RegistReceiverFEvent::SetReceiveHandler";
        }
        else
        {
            m_logger.LogError() << "FusionData::RegistReceiverFEvent::SetReceiveHandler::" << callback.Error().Message();
        }
    }
}
 
void FusionData::ReceiveEventFEventTriggered()
{
    if (m_found)
    {
        std::lock_guard<std::mutex> lock(m_mutex);
        if (m_interface->FEvent.GetSubscriptionState() == ara::com::SubscriptionState::kSubscribed)
        {
            auto recv = std::make_unique<ara::core::Result<size_t>>(m_interface->FEvent.GetNewSamples([&](auto samplePtr) {
                FusionData::ReadDataFEvent(std::move(samplePtr));
            }));
            if (recv->HasValue())
            {
                m_logger.LogVerbose() << "FusionData::ReceiveEventFEvent::GetNewSamples::" << recv->Value();
            }
            else
            {
                m_logger.LogError() << "FusionData::ReceiveEventFEvent::GetNewSamples::" << recv->Error().Message();
            }
        }
    }
}
 
void FusionData::ReceiveEventFEventCyclic()
{
    while (m_running)
    {
        std::lock_guard<std::mutex> lock(m_mutex);
        if (m_found)
        {
            if (m_interface->FEvent.GetSubscriptionState() == ara::com::SubscriptionState::kSubscribed)
            {
                auto recv = std::make_unique<ara::core::Result<size_t>>(m_interface->FEvent.GetNewSamples([&](auto samplePtr) {
                    FusionData::ReadDataFEvent(std::move(samplePtr));
                }));
                if (recv->HasValue())
                {
                    m_logger.LogVerbose() << "FusionData::ReceiveEventFEvent::GetNewSamples::" << recv->Value();
                }
                else
                {
                    m_logger.LogError() << "FusionData::ReceiveEventFEvent::GetNewSamples::" << recv->Error().Message();
                }
            }
        }
        std::this_thread::sleep_for(std::chrono::seconds(1));
    }
}
 
void FusionData::ReadDataFEvent(ara::com::SamplePtr<deepracer::service::fusiondata::proxy::events::FEvent::SampleType const> samplePtr)
{
    auto data = *samplePtr.Get();
    // put your logic

    m_logger.LogVerbose() << "FusionData::ReadDataFEvent::" << data;

    // FEvent 핸들러가 등록되어 있을시 해당 핸들러는 값과 함께 호출한다.
    if (m_receiveEventFEventHandler != nullptr)
    {
        m_receiveEventFEventHandler(data);
    }
}

// 개발자 추가 함수
// FEvent 수신에 대한 핸들러 등록 함수.
void FusionData::SetReceiveEventFEventHandler(
    std::function<void(const deepracer::service::fusiondata::proxy::events::FEvent::FEvent::SampleType&)> handler)
{
    m_receiveEventFEventHandler = handler;
}
 
} /// namespace port
} /// namespace aa
} /// namespace inference
 
/// EOF