///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : fusiondata.h
/// SOFTWARE COMPONENT NAME           : FusionData
/// GENERATED DATE                    : 2024-11-07 14:01:17
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_AA_GEN_SOFTWARE_COMPONENT_PPORT_SENSORFUSION_AA_FUSIONDATA_H
#define PARA_AA_GEN_SOFTWARE_COMPONENT_PPORT_SENSORFUSION_AA_FUSIONDATA_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "deepracer/service/fusiondata/svfusiondata_skeleton.h"
#include "deepracer/service/cameradata/svcameradata_proxy.h"
#include "deepracer/service/lidardata/svlidardata_proxy.h"
 
#include "ara/log/logger.h"
 
#include <mutex>
#include <thread>
 
namespace deepracer
{
namespace service
{
namespace fusiondata
{
namespace skeleton
{
 
class SvFusionDataSkeletonImpl : public SvFusionDataSkeleton
{
public:
    /// @brief Constructor
    SvFusionDataSkeletonImpl(ara::core::InstanceSpecifier instanceSpec, ara::com::MethodCallProcessingMode mode = ara::com::MethodCallProcessingMode::kEvent);
    
    /// @brief Request with Response method, FMethod
    //ara::core::Future<SvFusionDataSkeleton::FMethodOutput> FMethod() override;
    
    
private:
    /// @brief Logger for this port
    ara::log::Logger& m_logger;
    
    
};
 
} /// namespace skeleton
} /// namespace fusiondata
} /// namespace service
} /// namespace deepracer

namespace sensorfusion
{
namespace aa
{
namespace port
{
 
class FusionData
{
public:
    /// @brief Constructor
    FusionData();
    
    /// @brief Destructor
    ~FusionData();
    
    /// @brief Start port
    void Start();
    
    /// @brief Terminate port
    void Terminate();

    void WriteDataFEventCamera(const deepracer::type::CameraDataNode& data);

    void WriteDataFEventLidar(const deepracer::type::LidarDataNode& data);

    void SendEventFEventCyclic();
    
private:
    /// @brief Logger for this port
    ara::log::Logger& m_logger;
    
    /// @brief Flag of port status
    bool m_running;
    
    /// @brief Mutex for this port
    std::mutex m_mutex;
    
    /// @brief AUTOSAR Port Interface
    std::shared_ptr<deepracer::service::fusiondata::skeleton::SvFusionDataSkeletonImpl> m_interface;
    
    deepracer::service::fusiondata::skeleton::events::FEvent::SampleType m_FEventData;

    deepracer::service::cameradata::proxy::events::CEvent::SampleType m_CameraData;
    deepracer::service::lidardata::proxy::events::LEvent::SampleType m_LidarData;

};
 
} /// namespace port
} /// namespace aa
} /// namespace sensorfusion
 
#endif /// PARA_AA_GEN_SOFTWARE_COMPONENT_PPORT_SENSORFUSION_AA_FUSIONDATA_H