///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : sensorfusion.h
/// SOFTWARE COMPONENT NAME           : SensorFusion
/// GENERATED DATE                    : 2024-11-07 14:01:17
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_AA_GEN_SOFTWARE_COMPONENT_SENSORFUSION_AA_H
#define PARA_AA_GEN_SOFTWARE_COMPONENT_SENSORFUSION_AA_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "sensorfusion/aa/port/cameradata.h"
#include "sensorfusion/aa/port/fusiondata.h"
#include "sensorfusion/aa/port/lidardata.h"
 
#include "para/swc/port_pool.h"
 
namespace sensorfusion
{
namespace aa
{
 
class SensorFusion
{
public:
    /// @brief Constructor
    SensorFusion();
    
    /// @brief Destructor
    ~SensorFusion();
    
    /// @brief Initialize software component
    bool Initialize();
    
    /// @brief Start software component
    void Start();
    
    /// @brief Terminate software component
    void Terminate();
 
private:
    /// @brief Run software component
    void Run();

    void TaskReceiveCEventCyclic();

    void TaskReceiveLEventCyclic();

    //void OnReceiveCEvent();
    //void OnReceiveLEvent();
    void OnReceiveCEvent(const deepracer::type::CameraDataNode& sample);
    void OnReceiveLEvent(const deepracer::type::LidarDataNode& sample);

 
private:
    bool m_running;

    /// @brief Pool of port
    ::para::swc::PortPool m_workers;
    
    /// @brief Logger for software component
    ara::log::Logger& m_logger;
    
    /// @brief Instance of Port {SensorFusion.CameraData}
    std::shared_ptr<sensorfusion::aa::port::CameraData> m_CameraData;
    
    /// @brief Instance of Port {SensorFusion.FusionData}
    std::shared_ptr<sensorfusion::aa::port::FusionData> m_FusionData;
    
    /// @brief Instance of Port {SensorFusion.LidarData}
    std::shared_ptr<sensorfusion::aa::port::LidarData> m_LidarData;
};
 
} /// namespace aa
} /// namespace sensorfusion
 
#endif /// PARA_AA_GEN_SOFTWARE_COMPONENT_SENSORFUSION_AA_H