///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : servo.cpp
/// SOFTWARE COMPONENT NAME           : Servo
/// GENERATED DATE                    : 2024-11-07 14:01:17
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "servo/aa/servo.h"
#include "servo/aa/servo_mgr.hpp"
#include "servo/aa/led_mgr.hpp"

//json 사용
#include "json/json.h"

namespace servo
{
namespace aa
{
 
Servo::Servo()
    : m_logger(ara::log::CreateLogger("SRV", "SWC", ara::log::LogLevel::kVerbose))
    , m_workers(1)
{
}
 
Servo::~Servo()
{
}
 
bool Servo::Initialize()
{
    m_logger.LogVerbose() << "Servo::Initialize";
    
    bool init{true};
    
    m_NavigateData = std::make_shared<servo::aa::port::NavigateData>();
    
    return init;
}
 
void Servo::Start()
{
    m_logger.LogVerbose() << "Servo::Start";
    
    m_NavigateData->Start();
    
    // run software component
    Run();
}
 
void Servo::Terminate()
{
    m_logger.LogVerbose() << "Servo::Terminate";
    
    m_NavigateData->Terminate();
}
 
void Servo::Run()
{
    m_logger.LogVerbose() << "Servo::Run";
    
    //m_workers.Async([this] { m_NavigateData->ReceiveEventNEventCyclic(); });
    m_workers.Async([this] { TaskReceiveNEventCyclic(); });
    
    m_workers.Wait();
}

void Servo::TaskReceiveNEventCyclic()
{
    m_NavigateData->SetReceiveEventINventHandler([this](const auto& navigateMsg)
    {
        Drive(navigateMsg);
    });
    m_NavigateData->ReceiveEventNEventCyclic();
}

void Servo::Drive(const deepracer::service::navigatedata::proxy::events::NEvent::SampleType& navigateMsg)
{
    servoMgr->servoSubscriber(navigateMsg.throttle, navigateMsg.angle); 
}
 
} /// namespace aa
} /// namespace servo
