///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : navigate.h
/// SOFTWARE COMPONENT NAME           : Navigate
/// GENERATED DATE                    : 2024-10-25 13:47:26
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_AA_GEN_SOFTWARE_COMPONENT_NAVIGATE_AA_H
#define PARA_AA_GEN_SOFTWARE_COMPONENT_NAVIGATE_AA_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "navigate/aa/port/navigatedata.h"
#include "navigate/aa/port/inferencedata.h"
 
#include "para/swc/port_pool.h"
 
namespace navigate
{
namespace aa
{
 
class Navigate
{
public:
    /// @brief Constructor
    Navigate();
    
    /// @brief Destructor
    ~Navigate();
    
    /// @brief Initialize software component
    bool Initialize();
    
    /// @brief Start software component
    void Start();
    
    /// @brief Terminate software component
    void Terminate();
 
private:
    /// @brief Run software component
    void Run();
 
private:
    /// @brief Pool of port
    ::para::swc::PortPool m_workers;
    
    /// @brief Logger for software component
    ara::log::Logger& m_logger;
    
    /// @brief Instance of Port {Navigate.NavigateData}
    std::shared_ptr<navigate::aa::port::NavigateData> m_NavigateData;
    
    /// @brief Instance of Port {Navigate.InferenceData}
    std::shared_ptr<navigate::aa::port::InferenceData> m_InferenceData;
};
 
} /// namespace aa
} /// namespace navigate
 
#endif /// PARA_AA_GEN_SOFTWARE_COMPONENT_NAVIGATE_AA_H