///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : navigate.cpp
/// SOFTWARE COMPONENT NAME           : Navigate
/// GENERATED DATE                    : 2024-10-25 13:47:26
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "navigate/aa/navigate.h"
 
namespace navigate
{
namespace aa
{
 
Navigate::Navigate()
    : m_logger(ara::log::CreateLogger("NAV", "SWC", ara::log::LogLevel::kVerbose))
    , m_workers(2)
{
}
 
Navigate::~Navigate()
{
}
 
bool Navigate::Initialize()
{
    m_logger.LogVerbose() << "Navigate::Initialize";
    
    bool init{true};
    
    m_NavigateData = std::make_shared<navigate::aa::port::NavigateData>();
    m_InferenceData = std::make_shared<navigate::aa::port::InferenceData>();
    
    return init;
}
 
void Navigate::Start()
{
    m_logger.LogVerbose() << "Navigate::Start";
    
    m_NavigateData->Start();
    m_InferenceData->Start();
    
    // run software component
    Run();
}
 
void Navigate::Terminate()
{
    m_logger.LogVerbose() << "Navigate::Terminate";
    
    m_NavigateData->Terminate();
    m_InferenceData->Terminate();
}
 
void Navigate::Run()
{
    m_logger.LogVerbose() << "Navigate::Run";
    
    m_workers.Async([this] { m_NavigateData->SendEventNEventCyclic(); });
    m_workers.Async([this] { m_InferenceData->ReceiveEventIEventCyclic(); });
    
    m_workers.Wait();
}
 
} /// namespace aa
} /// namespace navigate
