///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : inferencedata.h
/// SOFTWARE COMPONENT NAME           : InferenceData
/// GENERATED DATE                    : 2024-10-25 13:47:26
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_AA_GEN_SOFTWARE_COMPONENT_PPORT_INFERENCE_AA_INFERENCEDATA_H
#define PARA_AA_GEN_SOFTWARE_COMPONENT_PPORT_INFERENCE_AA_INFERENCEDATA_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "deepracer/service/inferencedata/svinferencedata_skeleton.h"
 
#include "ara/log/logger.h"
 
#include <mutex>
#include <thread>
 
namespace deepracer
{
namespace service
{
namespace inferencedata
{
namespace skeleton
{
 
class SvInferenceDataSkeletonImpl : public SvInferenceDataSkeleton
{
public:
    /// @brief Constructor
    SvInferenceDataSkeletonImpl(ara::core::InstanceSpecifier instanceSpec, ara::com::MethodCallProcessingMode mode = ara::com::MethodCallProcessingMode::kEvent);
    
    
    
private:
    /// @brief Logger for this port
    ara::log::Logger& m_logger;
    
    
};
 
} /// namespace skeleton
} /// namespace inferencedata
} /// namespace service
} /// namespace deepracer

namespace inference
{
namespace aa
{
namespace port
{
 
class InferenceData
{
public:
    /// @brief Constructor
    InferenceData();
    
    /// @brief Destructor
    ~InferenceData();
    
    /// @brief Start port
    void Start();
    
    /// @brief Terminate port
    void Terminate();
    
    /// @brief Write event data to buffer, IEvent
    void WriteDataIEvent(const deepracer::service::inferencedata::skeleton::events::IEvent::SampleType& data);
     
    /// @brief Send event cyclic from buffer data, IEvent
    void SendEventIEventCyclic();
     
    /// @brief Send event directly from buffer data, IEvent
    void SendEventIEventTriggered();
     
    /// @brief Send event directly with argument, IEvent
    void SendEventIEventTriggered(const deepracer::service::inferencedata::skeleton::events::IEvent::SampleType& data);
     
private:
    /// @brief Logger for this port
    ara::log::Logger& m_logger;
    
    /// @brief Flag of port status
    bool m_running;
    
    /// @brief Mutex for this port
    std::mutex m_mutex;
    
    /// @brief AUTOSAR Port Interface
    std::shared_ptr<deepracer::service::inferencedata::skeleton::SvInferenceDataSkeletonImpl> m_interface;
    
    /// @brief Data for event, IEvent
    deepracer::service::inferencedata::skeleton::events::IEvent::SampleType m_IEventData;
};
 
} /// namespace port
} /// namespace aa
} /// namespace inference
 
#endif /// PARA_AA_GEN_SOFTWARE_COMPONENT_PPORT_INFERENCE_AA_INFERENCEDATA_H