///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : navigatedata.h
/// SOFTWARE COMPONENT NAME           : NavigateData
/// GENERATED DATE                    : 2024-11-07 14:01:17
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_AA_GEN_SOFTWARE_COMPONENT_PPORT_NAVIGATE_AA_NAVIGATEDATA_H
#define PARA_AA_GEN_SOFTWARE_COMPONENT_PPORT_NAVIGATE_AA_NAVIGATEDATA_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "deepracer/service/navigatedata/svnavigatedata_skeleton.h"
 
#include "ara/log/logger.h"
 
#include <mutex>
#include <thread>
 
namespace deepracer
{
namespace service
{
namespace navigatedata
{
namespace skeleton
{
 
class SvNavigateDataSkeletonImpl : public SvNavigateDataSkeleton
{
public:
    /// @brief Constructor
    SvNavigateDataSkeletonImpl(ara::core::InstanceSpecifier instanceSpec, ara::com::MethodCallProcessingMode mode = ara::com::MethodCallProcessingMode::kEvent);
    
    
    
private:
    /// @brief Logger for this port
    ara::log::Logger& m_logger;
    
    
};
 
} /// namespace skeleton
} /// namespace navigatedata
} /// namespace service
} /// namespace deepracer

namespace navigate
{
namespace aa
{
namespace port
{
 
class NavigateData
{
public:
    /// @brief Constructor
    NavigateData();
    
    /// @brief Destructor
    ~NavigateData();
    
    /// @brief Start port
    void Start();
    
    /// @brief Terminate port
    void Terminate();
    
    /// @brief Write event data to buffer, NEvent
    void WriteDataNEvent(const deepracer::service::navigatedata::skeleton::events::NEvent::SampleType& data);
     
    /// @brief Send event cyclic from buffer data, NEvent
    void SendEventNEventCyclic();
     
    /// @brief Send event directly from buffer data, NEvent
    void SendEventNEventTriggered();
     
    /// @brief Send event directly with argument, NEvent
    void SendEventNEventTriggered(const deepracer::service::navigatedata::skeleton::events::NEvent::SampleType& data);
     
private:
    /// @brief Logger for this port
    ara::log::Logger& m_logger;
    
    /// @brief Flag of port status
    bool m_running;
    
    /// @brief Mutex for this port
    std::mutex m_mutex;
    
    /// @brief AUTOSAR Port Interface
    std::shared_ptr<deepracer::service::navigatedata::skeleton::SvNavigateDataSkeletonImpl> m_interface;
    
    /// @brief Data for event, NEvent
    deepracer::service::navigatedata::skeleton::events::NEvent::SampleType m_NEventData;
};
 
} /// namespace port
} /// namespace aa
} /// namespace navigate
 
#endif /// PARA_AA_GEN_SOFTWARE_COMPONENT_PPORT_NAVIGATE_AA_NAVIGATEDATA_H