///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : camera.cpp
/// SOFTWARE COMPONENT NAME           : Camera
/// GENERATED DATE                    : 2024-10-25 13:47:26
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "camera/aa/camera.h"
 
namespace camera
{
namespace aa
{
 
Camera::Camera()
    : m_logger(ara::log::CreateLogger("CAM", "SWC", ara::log::LogLevel::kVerbose))
    , m_workers(1)
{
}
 
Camera::~Camera()
{
}
 
bool Camera::Initialize()
{
    m_logger.LogVerbose() << "Camera::Initialize";
    
    bool init{true};
    
    m_CameraData = std::make_shared<camera::aa::port::CameraData>();
    
    return init;
}
 
void Camera::Start()
{
    m_logger.LogVerbose() << "Camera::Start";
    
    m_CameraData->Start();
    
    // run software component
    Run();
}
 
void Camera::Terminate()
{
    m_logger.LogVerbose() << "Camera::Terminate";
    
    m_CameraData->Terminate();
}
 
void Camera::Run()
{
    m_logger.LogVerbose() << "Camera::Run";
    
    m_workers.Async([this] { m_CameraData->SendEventCEventCyclic(); });
    
    m_workers.Wait();
}
 
} /// namespace aa
} /// namespace camera
