///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : lidardata.cpp
/// SOFTWARE COMPONENT NAME           : LidarData
/// GENERATED DATE                    : 2024-10-25 13:47:26
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "sensorfusion/aa/port/lidardata.h"
 
namespace sensorfusion
{
namespace aa
{
namespace port
{
 
LidarData::LidarData()
    : m_logger(ara::log::CreateLogger("SSFU", "PORT", ara::log::LogLevel::kVerbose))
    , m_running{false}
    , m_found{false}
{
}
 
LidarData::~LidarData()
{
}
 
void LidarData::Start()
{
    m_logger.LogVerbose() << "LidarData::Start";
    
    // regist callback
    ara::core::InstanceSpecifier specifier{"SensorFusion/AA/LidarData"};
    auto handler = [this](ara::com::ServiceHandleContainer<deepracer::service::lidardata::proxy::SvLidarDataProxy::HandleType> handles,
                          ara::com::FindServiceHandle findHandle) {
        this->Find(handles, findHandle);
    };
    
    // find service
    auto find = deepracer::service::lidardata::proxy::SvLidarDataProxy::StartFindService(handler, specifier);
    if (find.HasValue())
    {
        m_logger.LogVerbose() << "LidarData::Start::StartFindService";
    }
    else
    {
        m_logger.LogError() << "LidarData::Start::StartFindService::" << find.Error().Message();
    }
    
    // run port
    m_running = true;
}
 
void LidarData::Terminate()
{
    m_logger.LogVerbose() << "LidarData::Terminate";
    
    // stop port
    m_running = false;
    
    // clear service proxy
    if (m_interface)
    {
        // stop subscribe
        StopSubscribeLEevent();
        
        // stop find service
        m_interface->StopFindService(*m_findHandle);
        m_found = false;
        
        m_logger.LogVerbose() << "LidarData::Terminate::StopFindService";
    }
}
 
void LidarData::Find(ara::com::ServiceHandleContainer<deepracer::service::lidardata::proxy::SvLidarDataProxy::HandleType> handles, ara::com::FindServiceHandle findHandle)
{
    // check finding handles
    if (handles.empty())
    {
        m_logger.LogVerbose() << "LidarData::Find::Service Instances not found";
        return;
    }
    else
    {
        for (auto& handle : handles)
        {
            m_logger.LogVerbose() << "LidarData::Find::Searched Instance::ServiceId =" << 
                                     handle.GetServiceHandle().serviceId << 
                                     ", InstanceId =" << 
                                     handle.GetServiceHandle().instanceId;
        }
    }
    
    // create proxy
    if (m_interface)
    {
        m_logger.LogVerbose() << "LidarData::Find::Proxy is already running";
    }
    else
    {
        m_logger.LogVerbose() << "LidarData::Find::Using Instance::ServiceId =" << 
                                 handles[0].GetServiceHandle().serviceId << 
                                 ", InstanceId =" << 
                                 handles[0].GetServiceHandle().instanceId;
        m_interface = std::make_shared<deepracer::service::lidardata::proxy::SvLidarDataProxy>(handles[0]);
        m_findHandle = std::make_shared<ara::com::FindServiceHandle>(findHandle);
        m_found = true;
        
        // subscribe events
        SubscribeLEevent();
    }
}
 
void LidarData::SubscribeLEevent()
{
    if (m_found)
    {
        // regist receiver handler
        // if you want to enable it, please uncomment below code
        // 
        // RegistReceiverLEevent();
        
        // request subscribe
        auto subscribe = m_interface->LEevent.Subscribe(1);
        if (subscribe.HasValue())
        {
            m_logger.LogVerbose() << "LidarData::SubscribeLEevent::Subscribed";
        }
        else
        {
            m_logger.LogError() << "LidarData::SubscribeLEevent::" << subscribe.Error().Message();
        }
    }
}
 
void LidarData::StopSubscribeLEevent()
{
    if (m_found)
    {
        // request stop subscribe
        m_interface->LEevent.Unsubscribe();
        m_logger.LogVerbose() << "LidarData::StopSubscribeLEevent::Unsubscribed";
    }
}
 
void LidarData::RegistReceiverLEevent()
{
    if (m_found)
    {
        // set callback
        auto receiver = [this]() -> void {
            return ReceiveEventLEeventTriggered();
        };
        
        // regist callback
        auto callback = m_interface->LEevent.SetReceiveHandler(receiver);
        if (callback.HasValue())
        {
            m_logger.LogVerbose() << "LidarData::RegistReceiverLEevent::SetReceiveHandler";
        }
        else
        {
            m_logger.LogError() << "LidarData::RegistReceiverLEevent::SetReceiveHandler::" << callback.Error().Message();
        }
    }
}
 
void LidarData::ReceiveEventLEeventTriggered()
{
    if (m_found)
    {
        std::lock_guard<std::mutex> lock(m_mutex);
        if (m_interface->LEevent.GetSubscriptionState() == ara::com::SubscriptionState::kSubscribed)
        {
            auto recv = std::make_unique<ara::core::Result<size_t>>(m_interface->LEevent.GetNewSamples([&](auto samplePtr) {
                LidarData::ReadDataLEevent(std::move(samplePtr));
            }));
            if (recv->HasValue())
            {
                m_logger.LogVerbose() << "LidarData::ReceiveEventLEevent::GetNewSamples::" << recv->Value();
            }
            else
            {
                m_logger.LogError() << "LidarData::ReceiveEventLEevent::GetNewSamples::" << recv->Error().Message();
            }
        }
    }
}
 
void LidarData::ReceiveEventLEeventCyclic()
{
    while (m_running)
    {
        std::lock_guard<std::mutex> lock(m_mutex);
        if (m_found)
        {
            if (m_interface->LEevent.GetSubscriptionState() == ara::com::SubscriptionState::kSubscribed)
            {
                auto recv = std::make_unique<ara::core::Result<size_t>>(m_interface->LEevent.GetNewSamples([&](auto samplePtr) {
                    LidarData::ReadDataLEevent(std::move(samplePtr));
                }));
                if (recv->HasValue())
                {
                    m_logger.LogVerbose() << "LidarData::ReceiveEventLEevent::GetNewSamples::" << recv->Value();
                }
                else
                {
                    m_logger.LogError() << "LidarData::ReceiveEventLEevent::GetNewSamples::" << recv->Error().Message();
                }
            }
        }
        std::this_thread::sleep_for(std::chrono::seconds(1));
    }
}
 
void LidarData::ReadDataLEevent(ara::com::SamplePtr<deepracer::service::lidardata::proxy::events::LEevent::SampleType const> samplePtr)
{
    auto data = *samplePtr.Get();
    // put your logic
}
 
} /// namespace port
} /// namespace aa
} /// namespace sensorfusion
 
/// EOF