///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : sm.h
/// SOFTWARE COMPONENT NAME           : SM
/// GENERATED DATE                    : 2024-10-25 13:47:26
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_AA_GEN_SOFTWARE_COMPONENT_SM_PARA_H
#define PARA_AA_GEN_SOFTWARE_COMPONENT_SM_PARA_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "sm/para/port/machinefg.h"
#include "sm/para/port/deepracerfg.h"
 
#include "para/swc/port_pool.h"
 
namespace sm
{
namespace para
{
 
class SM
{
public:
    /// @brief Constructor
    SM();
    
    /// @brief Destructor
    ~SM();
    
    /// @brief Initialize software component
    bool Initialize();
    
    /// @brief Start software component
    void Start();
    
    /// @brief Terminate software component
    void Terminate();
 
private:
    /// @brief Run software component
    void Run();
 
private:
    /// @brief Pool of port
    ::para::swc::PortPool m_workers;
    
    /// @brief Logger for software component
    ara::log::Logger& m_logger;
    
    /// @brief Instance of Port {SM.MachineFG}
    std::shared_ptr<sm::para::port::MachineFG> m_MachineFG;
    
    /// @brief Instance of Port {SM.DeepRacerFG}
    std::shared_ptr<sm::para::port::DeepRacerFG> m_DeepRacerFG;
};
 
} /// namespace para
} /// namespace sm
 
#endif /// PARA_AA_GEN_SOFTWARE_COMPONENT_SM_PARA_H