///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : navigatedata.cpp
/// SOFTWARE COMPONENT NAME           : NavigateData
/// GENERATED DATE                    : 2024-10-25 13:47:26
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "navigate/aa/port/navigatedata.h"
 
namespace deepracer
{
namespace service
{
namespace navigatedata
{
namespace skeleton
{
 
SvNavigateDataSkeletonImpl::SvNavigateDataSkeletonImpl(ara::core::InstanceSpecifier instanceSpec, ara::com::MethodCallProcessingMode mode)
    : SvNavigateDataSkeleton(instanceSpec, mode)
    , m_logger(ara::log::CreateLogger("NAV", "PORT", ara::log::LogLevel::kVerbose))
{
}
 
} /// namespace skeleton
} /// namespace navigatedata
} /// namespace service
} /// namespace deepracer

namespace navigate
{
namespace aa
{
namespace port
{
 
NavigateData::NavigateData()
    : m_logger(ara::log::CreateLogger("NAV", "PORT", ara::log::LogLevel::kVerbose))
    , m_running{false}
    , m_NEventData{0.0f, 0.0f, 0LL}
{
}
 
NavigateData::~NavigateData()
{
}
 
void NavigateData::Start()
{
    m_logger.LogVerbose() << "NavigateData::Start";
    
    // construct skeleton
    ara::core::InstanceSpecifier specifier{"Navigate/AA/NavigateData"};
    m_interface = std::make_shared<deepracer::service::navigatedata::skeleton::SvNavigateDataSkeletonImpl>(specifier);
    
    // offer service
    auto offer = m_interface->OfferService();
    if (offer.HasValue())
    {
        m_running = true;
        m_logger.LogVerbose() << "NavigateData::Start::OfferService";
    }
    else
    {
        m_running = false;
        m_logger.LogError() << "NavigateData::Start::OfferService::" << offer.Error().Message();
    }
}
 
void NavigateData::Terminate()
{
    m_logger.LogVerbose() << "NavigateData::Terminate";
    
    // stop port
    m_running = false;
    
    // stop offer service
    m_interface->StopOfferService();
    m_logger.LogVerbose() << "NavigateData::Terminate::StopOfferService";
}
 
void NavigateData::WriteDataNEvent(const deepracer::service::navigatedata::skeleton::events::NEvent::SampleType& data)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    m_NEventData = data;
}
 
void NavigateData::SendEventNEventCyclic()
{
    while (m_running)
    {
        {
            std::lock_guard<std::mutex> lock(m_mutex);
            auto send = m_interface->NEvent.Send(m_NEventData);
            if (send.HasValue())
            {
                m_logger.LogVerbose() << "NavigateData::SendEventNEventCyclic::Send";
            }
            else
            {
                m_logger.LogError() << "NavigateData::SendEventNEventCyclic::Send::" << send.Error().Message();
            }
        }
        std::this_thread::sleep_for(std::chrono::seconds(1));
    }
}
 
void NavigateData::SendEventNEventTriggered()
{
    std::lock_guard<std::mutex> lock(m_mutex);
    auto send = m_interface->NEvent.Send(m_NEventData);
    if (send.HasValue())
    {
        m_logger.LogVerbose() << "NavigateData::SendEventNEventTriggered::Send";
    }
    else
    {
        m_logger.LogError() << "NavigateData::SendEventNEventTriggered::Send::" << send.Error().Message();
    }
}
 
void NavigateData::SendEventNEventTriggered(const deepracer::service::navigatedata::skeleton::events::NEvent::SampleType& data)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    m_NEventData = data;
    auto send = m_interface->NEvent.Send(m_NEventData);
    if (send.HasValue())
    {
        m_logger.LogVerbose() << "NavigateData::SendEventNEventTriggered::Send";
    }
    else
    {
        m_logger.LogError() << "NavigateData::SendEventNEventTriggered::Send::" << send.Error().Message();
    }
}

} /// namespace port
} /// namespace aa
} /// namespace navigate
 
/// EOF