///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : sm.cpp
/// SOFTWARE COMPONENT NAME           : SM
/// GENERATED DATE                    : 2024-10-25 13:47:26
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "sm/para/sm.h"
 
namespace sm
{
namespace para
{
 
SM::SM()
    : m_logger(ara::log::CreateLogger("SM", "SWC", ara::log::LogLevel::kVerbose))
    , m_workers(2)
{
}
 
SM::~SM()
{
}
 
bool SM::Initialize()
{
    m_logger.LogVerbose() << "SM::Initialize";
    
    bool init{true};
    
    m_MachineFG = std::make_shared<sm::para::port::MachineFG>();
    m_DeepRacerFG = std::make_shared<sm::para::port::DeepRacerFG>();
    
    return init;
}
 
void SM::Start()
{
    m_logger.LogVerbose() << "SM::Start";
    
    m_MachineFG->Start();
    m_DeepRacerFG->Start();
    
    // run software component
    Run();
}
 
void SM::Terminate()
{
    m_logger.LogVerbose() << "SM::Terminate";
    
    m_MachineFG->Terminate();
    m_DeepRacerFG->Terminate();
}
 
void SM::Run()
{
    m_logger.LogVerbose() << "SM::Run";
    
    m_workers.Async([this] { m_MachineFG->NotifyMachineFGCyclic(); });
    m_workers.Async([this] { m_DeepRacerFG->NotifyDeepracerFGCyclic(); });
    
    m_workers.Wait();
}
 
} /// namespace para
} /// namespace sm
