///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : servo.h
/// SOFTWARE COMPONENT NAME           : Servo
/// GENERATED DATE                    : 2024-10-25 13:47:26
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_AA_GEN_SOFTWARE_COMPONENT_SERVO_AA_H
#define PARA_AA_GEN_SOFTWARE_COMPONENT_SERVO_AA_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "servo/aa/port/navigatedata.h"
 
#include "para/swc/port_pool.h"
 
namespace servo
{
namespace aa
{
 
class Servo
{
public:
    /// @brief Constructor
    Servo();
    
    /// @brief Destructor
    ~Servo();
    
    /// @brief Initialize software component
    bool Initialize();
    
    /// @brief Start software component
    void Start();
    
    /// @brief Terminate software component
    void Terminate();
 
private:
    /// @brief Run software component
    void Run();
    void TaskReceiveNEventCyclic()
    void Drive(const deepracer::service::navigatedata::proxy::events::NEvent::SampleType& navigateMsg)
 
private:
    /// @brief Pool of port
    ::para::swc::PortPool m_workers;
    
    /// @brief Logger for software component
    ara::log::Logger& m_logger;
    
    /// @brief Instance of Port {Servo.NavigateData}
    std::shared_ptr<servo::aa::port::NavigateData> m_NavigateData;
};
 
} /// namespace aa
} /// namespace servo
 
#endif /// PARA_AA_GEN_SOFTWARE_COMPONENT_SERVO_AA_H