///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : simulator.h
/// SOFTWARE COMPONENT NAME           : Simulator
/// GENERATED DATE                    : 2024-10-25 13:47:26
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_AA_GEN_SOFTWARE_COMPONENT_SIMULATOR_AA_H
#define PARA_AA_GEN_SOFTWARE_COMPONENT_SIMULATOR_AA_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "simulator/aa/port/simulatordata.h"
#include "simulator/aa/port/navigatedata.h"
 
#include "para/swc/port_pool.h"
 
namespace simulator
{
namespace aa
{
 
class Simulator
{
public:
    /// @brief Constructor
    Simulator();
    
    /// @brief Destructor
    ~Simulator();
    
    /// @brief Initialize software component
    bool Initialize();
    
    /// @brief Start software component
    void Start();
    
    /// @brief Terminate software component
    void Terminate();
 
private:
    /// @brief Run software component
    void Run();
 
private:
    /// @brief Pool of port
    ::para::swc::PortPool m_workers;
    
    /// @brief Logger for software component
    ara::log::Logger& m_logger;
    
    /// @brief Instance of Port {Simulator.SimulatorData}
    std::shared_ptr<simulator::aa::port::SimulatorData> m_SimulatorData;
    
    /// @brief Instance of Port {Simulator.NavigateData}
    std::shared_ptr<simulator::aa::port::NavigateData> m_NavigateData;
};
 
} /// namespace aa
} /// namespace simulator
 
#endif /// PARA_AA_GEN_SOFTWARE_COMPONENT_SIMULATOR_AA_H