///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : lidar.cpp
/// SOFTWARE COMPONENT NAME           : Lidar
/// GENERATED DATE                    : 2024-10-25 13:47:26
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "lidar/aa/lidar.h"
 
namespace lidar
{
namespace aa
{
 
Lidar::Lidar()
    : m_logger(ara::log::CreateLogger("LID", "SWC", ara::log::LogLevel::kVerbose))
    , m_workers(1)
{
}
 
Lidar::~Lidar()
{
}
 
bool Lidar::Initialize()
{
    m_logger.LogVerbose() << "Lidar::Initialize";
    
    bool init{true};
    
    m_Lidar = std::make_shared<lidar::aa::port::Lidar>();
    
    return init;
}
 
void Lidar::Start()
{
    m_logger.LogVerbose() << "Lidar::Start";
    
    m_Lidar->Start();
    
    // run software component
    Run();
}
 
void Lidar::Terminate()
{
    m_logger.LogVerbose() << "Lidar::Terminate";
    
    m_Lidar->Terminate();
}
 
void Lidar::Run()
{
    m_logger.LogVerbose() << "Lidar::Run";
    
    m_workers.Async([this] { m_Lidar->SendEventLEeventCyclic(); });
    
    m_workers.Wait();
}
 
} /// namespace aa
} /// namespace lidar
