///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : lidar.h
/// SOFTWARE COMPONENT NAME           : Lidar
/// GENERATED DATE                    : 2024-10-25 13:47:26
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_AA_GEN_SOFTWARE_COMPONENT_PPORT_LIDAR_AA_LIDAR_H
#define PARA_AA_GEN_SOFTWARE_COMPONENT_PPORT_LIDAR_AA_LIDAR_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "deepracer/service/lidardata/svlidardata_skeleton.h"
 
#include "ara/log/logger.h"
 
#include <mutex>
#include <thread>
 
namespace deepracer
{
namespace service
{
namespace lidardata
{
namespace skeleton
{
 
class SvLidarDataSkeletonImpl : public SvLidarDataSkeleton
{
public:
    /// @brief Constructor
    SvLidarDataSkeletonImpl(ara::core::InstanceSpecifier instanceSpec, ara::com::MethodCallProcessingMode mode = ara::com::MethodCallProcessingMode::kEvent);
    
    
    
private:
    /// @brief Logger for this port
    ara::log::Logger& m_logger;
    
    
};
 
} /// namespace skeleton
} /// namespace lidardata
} /// namespace service
} /// namespace deepracer

namespace lidar
{
namespace aa
{
namespace port
{
 
class Lidar
{
public:
    /// @brief Constructor
    Lidar();
    
    /// @brief Destructor
    ~Lidar();
    
    /// @brief Start port
    void Start();
    
    /// @brief Terminate port
    void Terminate();
    
    /// @brief Write event data to buffer, LEevent
    void WriteDataLEevent(const deepracer::service::lidardata::skeleton::events::LEevent::SampleType& data);
     
    /// @brief Send event cyclic from buffer data, LEevent
    void SendEventLEeventCyclic();
     
    /// @brief Send event directly from buffer data, LEevent
    void SendEventLEeventTriggered();
     
    /// @brief Send event directly with argument, LEevent
    void SendEventLEeventTriggered(const deepracer::service::lidardata::skeleton::events::LEevent::SampleType& data);
     
private:
    /// @brief Logger for this port
    ara::log::Logger& m_logger;
    
    /// @brief Flag of port status
    bool m_running;
    
    /// @brief Mutex for this port
    std::mutex m_mutex;
    
    /// @brief AUTOSAR Port Interface
    std::shared_ptr<deepracer::service::lidardata::skeleton::SvLidarDataSkeletonImpl> m_interface;
    
    /// @brief Data for event, LEevent
    deepracer::service::lidardata::skeleton::events::LEevent::SampleType m_LEeventData;
};
 
} /// namespace port
} /// namespace aa
} /// namespace lidar
 
#endif /// PARA_AA_GEN_SOFTWARE_COMPONENT_PPORT_LIDAR_AA_LIDAR_H