///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : lidar.cpp
/// SOFTWARE COMPONENT NAME           : Lidar
/// GENERATED DATE                    : 2024-10-25 13:47:26
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "lidar/aa/port/lidar.h"
 
namespace deepracer
{
namespace service
{
namespace lidardata
{
namespace skeleton
{
 
SvLidarDataSkeletonImpl::SvLidarDataSkeletonImpl(ara::core::InstanceSpecifier instanceSpec, ara::com::MethodCallProcessingMode mode)
    : SvLidarDataSkeleton(instanceSpec, mode)
    , m_logger(ara::log::CreateLogger("LID", "PORT", ara::log::LogLevel::kVerbose))
{
}
 
} /// namespace skeleton
} /// namespace lidardata
} /// namespace service
} /// namespace deepracer

namespace lidar
{
namespace aa
{
namespace port
{
 
Lidar::Lidar()
    : m_logger(ara::log::CreateLogger("LID", "PORT", ara::log::LogLevel::kVerbose))
    , m_running{false}
    , m_LEeventData{0LL, {{0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, {0.0f, 0.0f, 0.0f}, {0.0f, 0.0f, 0.0f}}, {0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, {0.0f, 0.0f, 0.0f}, {0.0f, 0.0f, 0.0f}}, {0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, {0.0f, 0.0f, 0.0f}, {0.0f, 0.0f, 0.0f}}}}
{
}
 
Lidar::~Lidar()
{
}
 
void Lidar::Start()
{
    m_logger.LogVerbose() << "Lidar::Start";
    
    // construct skeleton
    ara::core::InstanceSpecifier specifier{"Lidar/AA/Lidar"};
    m_interface = std::make_shared<deepracer::service::lidardata::skeleton::SvLidarDataSkeletonImpl>(specifier);
    
    // offer service
    auto offer = m_interface->OfferService();
    if (offer.HasValue())
    {
        m_running = true;
        m_logger.LogVerbose() << "Lidar::Start::OfferService";
    }
    else
    {
        m_running = false;
        m_logger.LogError() << "Lidar::Start::OfferService::" << offer.Error().Message();
    }
}
 
void Lidar::Terminate()
{
    m_logger.LogVerbose() << "Lidar::Terminate";
    
    // stop port
    m_running = false;
    
    // stop offer service
    m_interface->StopOfferService();
    m_logger.LogVerbose() << "Lidar::Terminate::StopOfferService";
}
 
void Lidar::WriteDataLEevent(const deepracer::service::lidardata::skeleton::events::LEevent::SampleType& data)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    m_LEeventData = data;
}
 
void Lidar::SendEventLEeventCyclic()
{
    while (m_running)
    {
        {
            std::lock_guard<std::mutex> lock(m_mutex);
            auto send = m_interface->LEevent.Send(m_LEeventData);
            if (send.HasValue())
            {
                m_logger.LogVerbose() << "Lidar::SendEventLEeventCyclic::Send";
            }
            else
            {
                m_logger.LogError() << "Lidar::SendEventLEeventCyclic::Send::" << send.Error().Message();
            }
        }
        std::this_thread::sleep_for(std::chrono::seconds(1));
    }
}
 
void Lidar::SendEventLEeventTriggered()
{
    std::lock_guard<std::mutex> lock(m_mutex);
    auto send = m_interface->LEevent.Send(m_LEeventData);
    if (send.HasValue())
    {
        m_logger.LogVerbose() << "Lidar::SendEventLEeventTriggered::Send";
    }
    else
    {
        m_logger.LogError() << "Lidar::SendEventLEeventTriggered::Send::" << send.Error().Message();
    }
}
 
void Lidar::SendEventLEeventTriggered(const deepracer::service::lidardata::skeleton::events::LEevent::SampleType& data)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    m_LEeventData = data;
    auto send = m_interface->LEevent.Send(m_LEeventData);
    if (send.HasValue())
    {
        m_logger.LogVerbose() << "Lidar::SendEventLEeventTriggered::Send";
    }
    else
    {
        m_logger.LogError() << "Lidar::SendEventLEeventTriggered::Send::" << send.Error().Message();
    }
}
 
} /// namespace port
} /// namespace aa
} /// namespace lidar
 
/// EOF