///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : lidardata.cpp
/// SOFTWARE COMPONENT NAME           : LidarData
/// GENERATED DATE                    : 2024-11-07 14:01:17
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "lidar/aa/port/lidardata.h"
 
using namespace sl;
 
namespace deepracer
{
namespace service
{
namespace lidardata
{
namespace skeleton
{
 
SvLidarDataSkeletonImpl::SvLidarDataSkeletonImpl(ara::core::InstanceSpecifier instanceSpec, ara::com::MethodCallProcessingMode mode)
    : SvLidarDataSkeleton(instanceSpec, mode)
    , m_logger(ara::log::CreateLogger("LID", "PORT", ara::log::LogLevel::kVerbose))
{
}
 
} /// namespace skeleton
} /// namespace lidardata
} /// namespace service
} /// namespace deepracer

namespace lidar
{
namespace aa
{
namespace port
{
 
LidarData::LidarData()
    : m_logger(ara::log::CreateLogger("LID", "PORT", ara::log::LogLevel::kVerbose))
    , m_running{false}
    , m_LEventData{0LL, {0.0f, 0.0f, 0.0f}}
{
}

LidarData::~LidarData()
{
}
 
void LidarData::Start()
{
    m_logger.LogVerbose() << "LidarData::Start";
    
    // construct skeleton
    ara::core::InstanceSpecifier specifier{"Lidar/AA/LidarData"};
    m_interface = std::make_shared<deepracer::service::lidardata::skeleton::SvLidarDataSkeletonImpl>(specifier);
    
    // offer service
    auto offer = m_interface->OfferService();
    if (offer.HasValue())
    {
        m_running = true;
        m_logger.LogVerbose() << "LidarData::Start::OfferService";
    }
    else
    {
        m_running = false;
        m_logger.LogError() << "LidarData::Start::OfferService::" << offer.Error().Message();
    }
}

void LidarData::Terminate()
{
    m_logger.LogVerbose() << "LidarData::Terminate";
    
    // stop port
    m_running = false;
    
    // stop offer service
    m_interface->StopOfferService();
    m_logger.LogVerbose() << "LidarData::Terminate::StopOfferService";
}
 
void LidarData::produceScanning() {
    if (!m_drv) {
        m_logger.LogError() << "Lidar driver is not initialized.";
        return;
    }

    deepracer::service::lidardata::skeleton::events::LEvent::SampleType& scan_data;

    sl_lidar_response_measurement_node_hq_t nodes[8192];
    size_t count = sizeof(nodes) / sizeof(sl_lidar_response_measurement_node_hq_t);

    // 데이터 캡처
    auto op_result = m_drv->grabScanDataHq(nodes, count);

    if (SL_IS_OK(op_result)) {
        m_drv->ascendScanData(nodes, count);

        for (size_t pos = 0; pos < (int)count; ++pos) {
            // 캡처한 데이터를 scan_data에 저장
            scan_data.scans[pos].distance = nodes[pos].dist_mm_q2 / 4.0f;
            scan_data.scans[pos].angle = (nodes[pos].angle_z_q14 * 90.f) / 16384.f;
            scan_data.scans[pos].qual = nodes[pos].quality >> SL_LIDAR_RESP_MEASUREMENT_QUALITY_SHIFT;
        }

        scan_data.timestamp = getCurrentTimestamp();
        
        WriteDataLEvent(scan_data);
    } else {
        m_logger.LogError() << "Failed to grab scan data from Lidar.";
    }
}

int64_t LidarData::getCurrentTimestamp() const {
    using namespace std::chrono;
    return duration_cast<milliseconds>(system_clock::now().time_since_epoch()).count();
}

void LidarData::WriteDataLEvent(const deepracer::service::lidardata::skeleton::events::LEvent::SampleType& data)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    m_LEventData = data;
}

void LidarData::SendEventLEventCyclic()
{
    while (m_running)
    {
        {
            std::lock_guard<std::mutex> lock(m_mutex);
            auto send = m_interface->LEvent.Send(m_LEventData);
            if (send.HasValue())
            {
                m_logger.LogVerbose() << "LidarData::SendEventLEventCyclic::Send";
            }
            else
            {
                m_logger.LogError() << "LidarData::SendEventLEventCyclic::Send::" << send.Error().Message();
            }
        }
        std::this_thread::sleep_for(std::chrono::seconds(1));
    }
}
 
void LidarData::SendEventLEventTriggered()
{
    std::lock_guard<std::mutex> lock(m_mutex);
    auto send = m_interface->LEvent.Send(m_LEventData);
    if (send.HasValue())
    {
        m_logger.LogVerbose() << "LidarData::SendEventLEventTriggered::Send";
    }
    else
    {
        m_logger.LogError() << "LidarData::SendEventLEventTriggered::Send::" << send.Error().Message();
    }
}
 
void LidarData::SendEventLEventTriggered(const deepracer::service::lidardata::skeleton::events::LEvent::SampleType& data)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    m_LEventData = data;
    auto send = m_interface->LEvent.Send(m_LEventData);
    if (send.HasValue())
    {
        m_logger.LogVerbose() << "LidarData::SendEventLEventTriggered::Send";
    }
    else
    {
        m_logger.LogError() << "LidarData::SendEventLEventTriggered::Send::" << send.Error().Message();
    }
}

 
} /// namespace port
} /// namespace aa
} /// namespace lidar
 
/// EOF